apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ .Values.streamLauncher1.name }}
spec:
  interval: 2m
  chart:
    spec:
      chart: stream-launcher
      sourceRef:
        kind: HelmRepository
        name: ott
        namespace: flux-system
      version: {{ .Values.streamLauncher1.version}}
  values:
    upstreamUrl: {{ .Values.streamLauncher1.upstreamUrl }}
    imagePullSecrets:
      - name: ott-ghcr-io
