name: Release Charts

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Custom packaging
        run : |
          VERSION=${{ github.ref.name }}
          echo "Packaging version ${VERSION:1}"
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          helm package charts/ --app-version=${VERSION:1} --v=${VERSION:1} --destination_.cr-release-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"